name: Zip Files

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '*' 
  pull_request:
    branches: [ master ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Folder
        run: zip -r ${{ github.workspace }}.zip . -x ".git/*" ".github/* ${{ github.workspace }}.zip"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.workspace }}.zip
          git commit -m "Release" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
